[package]
name = "avidf-task-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
zip = "0.5"

[lib]
name = "hashlib"
path = "src/lib.rs"